### ISSUE TITLE
Selecting an area in a map returns more than just the tile selected (probably unkown)

### ISSUE THREAD

**Issue by Yoyasp** [HU-R2D2/map#13]
![image](https://cloud.githubusercontent.com/assets/5970586/16011415/bee74408-3185-11e6-892a-9f833aa3e24c.png) This should select Navigatable instead of mixed

![image](https://cloud.githubusercontent.com/assets/5970586/16011457/f15f5c4a-3185-11e6-81bc-b8303cffdc49.png) This does return the correct boxInfo

So x size does matter, but y size doesnt.

**Comment by chieltbest** [comment]
confirmed fixed in the most recent version of the code (2929d0fdfb510f81c68d3631312c97b901826ee0)
