### ISSUE TITLE
set_box_info works like a mask....

### ISSUE THREAD

**Issue by florenso** [HU-R2D2/map#6]
![image](https://cloud.githubusercontent.com/assets/9743844/14769536/2a93262e-0a5b-11e6-999a-4ba1c49cd939.png)

![image](https://cloud.githubusercontent.com/assets/9743844/14769540/3c326dea-0a5b-11e6-9b97-f7b887c79feb.png)

hier de code nog in text zodat je kan knippen en plakken:
std::cout << "is now " << map->get_box_info(tile).get_has_navigatable() <<
                     map->get_box_info(tile).get_has_obstacle() <<
                     map->get_box_info(tile).get_has_unknown() << std::endl;
        std::cout << "needs to be " << info.get_has_navigatable() <<
                     info.get_has_obstacle() <<
                     info.get_has_unknown() << std::endl;
        map->set_box_info(tile, info);
        std::cout << "but is " << map->get_box_info(tile).get_has_navigatable() <<
                     map->get_box_info(tile).get_has_obstacle() <<
                     map->get_box_info(tile).get_has_unknown() << std::endl;

**Comment by chieltbest** [comment]
Confirmed unreproducible in latest commit (commit 127a9e4ab808fb272b3803f5f699b1736a995555)

```
is now 001
needs to be 010
but is 010
```

complete reprod:

```
TEST(Testy, Test) {
    r2d2::ArrayBoxMap map{};
    r2d2::Box tile{r2d2::Coordinate{-1 * r2d2::Length::METER,
                                    -1 * r2d2::Length::METER,
                                    -1 * r2d2::Length::METER},
                   r2d2::Coordinate{1 * r2d2::Length::METER,
                                    1 * r2d2::Length::METER,
                                    1 * r2d2::Length::METER}};
    r2d2::BoxInfo info{true, false, false};
    std::cout << "is now " << map.get_box_info(tile).get_has_navigatable() <<
                                           map.get_box_info(tile).get_has_obstacle() <<
                                           map.get_box_info(tile).get_has_unknown() << std::endl;
    std::cout << "needs to be " << info.get_has_navigatable() <<
                                                    info.get_has_obstacle() <<
                                                    info.get_has_unknown() << std::endl;
    map.set_box_info(tile, info);
    std::cout << "but is " << map.get_box_info(tile).get_has_navigatable() <<
                                          map.get_box_info(tile).get_has_obstacle() <<
                                          map.get_box_info(tile).get_has_unknown() << std::endl;
}
```
